# Permalinks
permalink:        pretty

gems:
  - jekyll-paginate

# Setup
title:            Exaile
tagline:          Music Player for GTK+
url:              http://exaile.github.io
paginate:         5
baseurl:          /
author:
  name:           Exaile Developer Team
  url:            http://www.exaile.org
  email:          exaile-devel@googlegroups.com

# Menu setup
menu:
    - ["Get It", "/download/"]
    - ["Screenshots", "/screens/"]
    - ["Docs", "http://exaile.readthedocs.org"]
    - ["Support", "/support"]
    - ["Code", "https://github.com/exaile/exaile"]
    - ["Bugs", "https://github.com/exaile/exaile/issues"]

# Exaile versions, used in various places
exaile:
  version:        4.2.0-alpha1
  srcver:         4.2.0-alpha1
  osxver:         4.2.0-alpha1
  winver:         4.2.0-alpha1

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/exaile/exaile.github.io
